{
 "title": "Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "url",
    "label": "Url",
    "query": {
     "query": "label_values(ws_rpc_health, url)\n"
    }
   },
   {
    "name": "blockchain",
    "label": "Blockchain",
    "query": {
     "query": "label_values(ws_rpc_health, blockchain)\n"
    }
   },
   {
    "name": "network_name",
    "label": "Network Name",
    "query": {
     "query": "label_values(ws_rpc_health, network_name)\n"
    }
   },
   {
    "name": "network_type",
    "label": "Network Type",
    "query": {
     "query": "label_values(ws_rpc_health, network_type)\n"
    }
   },
   {
    "name": "provider",
    "label": "Provider",
    "query": {
     "query": "label_values(ws_rpc_health, provider)\n"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "ws_rpc_health{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Node SLA Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ws_rpc_sla_compliant{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Node Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ws_rpc_block_height{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Block Height Deviation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "ws_rpc_block_height_behind_highest{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Node Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ws_rpc_latency{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Node Disconnects Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ws_rpc_disconnects_total{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  },
  {
   "title": "Node Log Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ws_rpc_log_count_total{url=~\"$url\", blockchain=~\"$blockchain\", network_name=~\"$network_name\", network_type=~\"$network_type\", provider=~\"$provider\"}",
     "legendFormat": "{{ url }}"
    }
   ]
  }
 ]
}